# Generated by Django 4.0.4 on 2022-05-15 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100)),
                ('targets_number', models.PositiveIntegerField()),
                ('rimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('rregion', models.CharField(max_length=150)),
                ('rdistrict', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=100)),
                ('k1value', models.PositiveIntegerField()),
                ('k2value', models.PositiveIntegerField()),
                ('k3value', models.PositiveIntegerField()),
                ('timage', models.ImageField(blank=True, null=True, upload_to='')),
                ('resevoirid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.reservoir')),
                ('t_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=100)),
                ('parametres', models.CharField(max_length=250)),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('targetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.target')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hvalue', models.PositiveIntegerField()),
                ('h_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('htargetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.target')),
                ('indicatorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.indicator')),
                ('reservoirid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.reservoir')),
            ],
        ),
    ]
