# Generated by Django 4.0.4 on 2022-05-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='reservoirid',
            new_name='hreservoirid',
        ),
    ]
